name: countermine-vpr
channels:
  - defaults
  - xformers
  - pytorch
  - nvidia
dependencies:
  - python=3.10
  - pytorch::pytorch=2.1.0
  - pytorch::torchvision=0.16.0
  - pytorch::pytorch-cuda=12.1
  - mkl<2024.1
  - numpy=1.26.4
  - pillow
  - tqdm
  - pip
  - setuptools<81
  - pip:
      - pytorch-lightning==2.1.2
      - pytorch-metric-learning==2.3.0
      - torchmetrics==1.2.0
      - pandas==2.1.3
      - prettytable==3.9.0
      - xformers==0.0.22.post7
      - faiss-gpu==1.7.2
      - matplotlib
      - tensorboard
      - wandb
